version: "3"
services:
  postgres:
    image: postgres:alpine
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lairs
  rso-customers:
    image: rlamp/lairbnb-lairs
    ports:
      - 8081:8081
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/lairs
    depends_on:
      - postgres