kumuluzee:
  name: lairbnb-lairs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/LairsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/lairs
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/LairsDS
      etcd-health-check:
        connection-url: http://192.168.99.100:2379/health
      http-health-check:
        - connection-url: http://192.168.99.100:8080/v1/users
        - connection-url: http://192.168.99.100:8082/v1/reservations
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
    - name: lairs-endpoint
      url-pattern: /v1/lairs/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="notifications">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="9133958c-d366-47ba-8103-32d02e80e198-ls.logit.io" port="14664"
                                                                                                        protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8"
                                                                                                    properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'


service-properties:
  service:
    healthy: true
  external-services:
    user-service:
      enabled: true
    reservation-service:
      enabled: true