kumuluzee:
  name: lairbnb-lairs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/LairsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/lairs
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379

service-properties:
  external-services:
    user-service:
      enabled: true
    reservation-service:
      enabled: true