insert into lair (owner_id, address, city, country, beds, price) values (11, '1083 Bluejay Road', 'Parungjawa', 'Indonesia', 3, 86.63);
insert into lair (owner_id, address, city, country, beds, price) values (22, '375 Oxford Point', 'Kudanding', 'Philippines', 5, 14.99);
insert into lair (owner_id, address, city, country, beds, price) values (10, '18602 Spohn Parkway', 'Lungaog', 'Philippines', 5, 54.87);
insert into lair (owner_id, address, city, country, beds, price) values (8, '1522 Green Point', 'Ape', 'Latvia', 2, 28.03);
insert into lair (owner_id, address, city, country, beds, price) values (23, '20951 Mcguire Junction', 'Fortuna', 'Costa Rica', 4, 56.88);
insert into lair (owner_id, address, city, country, beds, price) values (26, '7067 Thierer Terrace', 'Liski', 'Russia', 4, 57.88);
insert into lair (owner_id, address, city, country, beds, price) values (34, '03976 Moulton Avenue', 'Locminé', 'France', 4, 28.03);
insert into lair (owner_id, address, city, country, beds, price) values (7, '75393 Elmside Alley', 'Conduaga', 'Philippines', 1, 46.75);
insert into lair (owner_id, address, city, country, beds, price) values (3, '75360 Lillian Place', 'Dengzishan', 'China', 1, 9.07);
insert into lair (owner_id, address, city, country, beds, price) values (33, '33 Gulseth Court', 'Hương Sơn', 'Vietnam', 3, 23.81);
insert into lair (owner_id, address, city, country, beds, price) values (23, '807 Bartelt Lane', 'Davydovo', 'Russia', 2, 66.92);
insert into lair (owner_id, address, city, country, beds, price) values (7, '0 New Castle Avenue', 'Višnjićevo', 'Serbia', 5, 51.89);
insert into lair (owner_id, address, city, country, beds, price) values (6, '422 Harper Drive', 'Bandaragung', 'Indonesia', 1, 93.96);
insert into lair (owner_id, address, city, country, beds, price) values (16, '385 Summit Street', 'Sampacho', 'Argentina', 1, 51.89);
insert into lair (owner_id, address, city, country, beds, price) values (23, '986 Bluejay Alley', 'Danidehe', 'Indonesia', 5, 19.43);
insert into lair (owner_id, address, city, country, beds, price) values (29, '7988 Bowman Alley', 'Ibara', 'Japan', 3, 26.01);
insert into lair (owner_id, address, city, country, beds, price) values (26, '379 Marquette Parkway', 'Alamar', 'Cuba', 3, 61.46);
insert into lair (owner_id, address, city, country, beds, price) values (29, '661 Bowman Pass', 'Camindangan', 'Philippines', 2, 39.47);
insert into lair (owner_id, address, city, country, beds, price) values (11, '80 Sloan Street', 'Dangchang Chengguanzhen', 'China', 5, 86.13);
insert into lair (owner_id, address, city, country, beds, price) values (36, '262 Vermont Court', 'Gesik', 'Indonesia', 3, 19.14);
insert into lair (owner_id, address, city, country, beds, price) values (8, '1 Reinke Alley', 'Šardice', 'Czech Republic', 5, 64.97);
insert into lair (owner_id, address, city, country, beds, price) values (9, '0 Harbort Alley', 'Jinpanling', 'China', 2, 48.73);
insert into lair (owner_id, address, city, country, beds, price) values (7, '0823 Fulton Parkway', 'São Martinho de Árvore', 'Portugal', 2, 52.97);
insert into lair (owner_id, address, city, country, beds, price) values (5, '2022 Miller Crossing', 'Phùng', 'Vietnam', 3, 78.9);
insert into lair (owner_id, address, city, country, beds, price) values (11, '40 Jackson Parkway', 'Al Qadmūs', 'Syria', 5, 87.82);
insert into lair (owner_id, address, city, country, beds, price) values (5, '9433 Glendale Court', 'Río Bueno', 'Chile', 4, 52.64);
insert into lair (owner_id, address, city, country, beds, price) values (23, '546 Vidon Circle', 'Sinubong', 'Philippines', 4, 96.64);
insert into lair (owner_id, address, city, country, beds, price) values (4, '190 Monterey Terrace', 'Uluale', 'Indonesia', 5, 41.57);
insert into lair (owner_id, address, city, country, beds, price) values (26, '8532 Stuart Plaza', 'Primero de Mayo', 'Mexico', 1, 35.43);
insert into lair (owner_id, address, city, country, beds, price) values (4, '2963 Dayton Avenue', 'Caldas Novas', 'Brazil', 5, 79.99);
insert into lair (owner_id, address, city, country, beds, price) values (33, '5818 Pierstorff Drive', 'Guicheng', 'China', 4, 10.1);
insert into lair (owner_id, address, city, country, beds, price) values (25, '17885 Old Shore Way', 'Bom Jesus do Itabapoana', 'Brazil', 4, 81.53);
insert into lair (owner_id, address, city, country, beds, price) values (1, '50 Clove Way', '‘Ayn an Nasr', 'Syria', 5, 89.97);
insert into lair (owner_id, address, city, country, beds, price) values (19, '440 Mayfield Court', 'Biting', 'Indonesia', 1, 69.12);
insert into lair (owner_id, address, city, country, beds, price) values (10, '212 Eggendart Hill', 'Qacha’s Nek', 'Lesotho', 3, 77.53);
insert into lair (owner_id, address, city, country, beds, price) values (32, '0 Sycamore Road', 'Mangunjaya', 'Indonesia', 3, 26.17);
insert into lair (owner_id, address, city, country, beds, price) values (33, '4 Brickson Park Road', 'Tanjungpecinan Utara', 'Indonesia', 5, 13.71);
insert into lair (owner_id, address, city, country, beds, price) values (21, '919 Northwestern Street', 'Setun’', 'Russia', 4, 57.46);
insert into lair (owner_id, address, city, country, beds, price) values (17, '114 Lindbergh Lane', 'Argungu', 'Nigeria', 1, 96.66);
insert into lair (owner_id, address, city, country, beds, price) values (35, '1 Esch Pass', 'As Suwaydā', 'Yemen', 1, 15.29);
insert into lair (owner_id, address, city, country, beds, price) values (36, '978 Pine View Drive', 'Amnat Charoen', 'Thailand', 1, 99.72);
insert into lair (owner_id, address, city, country, beds, price) values (20, '96467 Del Sol Park', 'Wanganui', 'New Zealand', 3, 81.17);
insert into lair (owner_id, address, city, country, beds, price) values (5, '2086 Golf Course Avenue', 'Cuamba', 'Mozambique', 5, 91.91);
insert into lair (owner_id, address, city, country, beds, price) values (18, '42 Bobwhite Junction', 'Mburukullu', 'Indonesia', 5, 68.11);
insert into lair (owner_id, address, city, country, beds, price) values (1, '989 Gina Parkway', 'Pakusari', 'Indonesia', 2, 31.18);
insert into lair (owner_id, address, city, country, beds, price) values (33, '43455 Oak Valley Junction', 'Wangon', 'Indonesia', 5, 90.8);
insert into lair (owner_id, address, city, country, beds, price) values (10, '78285 Ryan Parkway', 'Vila Verde', 'Portugal', 5, 25.6);
insert into lair (owner_id, address, city, country, beds, price) values (19, '5669 Stephen Park', 'Mysiadło', 'Poland', 5, 56.45);
insert into lair (owner_id, address, city, country, beds, price) values (36, '52000 Dawn Parkway', 'Itaperuna', 'Brazil', 5, 56.87);
insert into lair (owner_id, address, city, country, beds, price) values (31, '8 Golden Leaf Alley', 'Tenggun Dajah', 'Indonesia', 4, 42.41);
insert into lair (owner_id, address, city, country, beds, price) values (8, '1 Ridgeway Hill', 'Apoya', 'Philippines', 5, 56.53);
insert into lair (owner_id, address, city, country, beds, price) values (17, '6 Aberg Street', 'Raejeru', 'Indonesia', 1, 57.6);
insert into lair (owner_id, address, city, country, beds, price) values (16, '992 Northview Drive', 'Ostrów Lubelski', 'Poland', 2, 38.28);
insert into lair (owner_id, address, city, country, beds, price) values (22, '5002 Pierstorff Lane', 'Wuli', 'China', 5, 58.82);
insert into lair (owner_id, address, city, country, beds, price) values (39, '355 Debra Lane', 'Eskilstuna', 'Sweden', 4, 57.21);
insert into lair (owner_id, address, city, country, beds, price) values (13, '2604 West Center', 'Ouanaminthe', 'Haiti', 5, 38.8);
insert into lair (owner_id, address, city, country, beds, price) values (7, '055 Ridgeview Drive', 'Liping', 'China', 1, 17.0);
insert into lair (owner_id, address, city, country, beds, price) values (26, '6 Bunker Hill Way', 'Hikari', 'Japan', 5, 19.56);
insert into lair (owner_id, address, city, country, beds, price) values (1, '255 Blue Bill Park Center', 'Jadowniki', 'Poland', 4, 30.71);
insert into lair (owner_id, address, city, country, beds, price) values (26, '638 Kropf Junction', 'Kaédi', 'Mauritania', 4, 78.3);
