apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-lairs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-lairs
    spec:
      containers:
        - image: postgres:10.1
          name: postgres-lairs
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: lairs
          ports:
          - containerPort: 5432
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-lairs
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-lairs